language: python
services:
  - redis-server
matrix:
  fast_finish: true
  include:
  - python: "2.7"
  - python: "3.4"
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
    dist: xenial
  - python: "pypy"

# command to install dependencies
install:
  - bash -c '[[ $(python -V) == "Python 3.4."* ]] && pip install setuptools==24.0.3 || :'
  - pip install -r requirements.txt
# command to run tests
script:
  - nosetests -s
