language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
services:
  - redis-server
matrix:
  - fast_finish: true
# command to install dependencies
install:
  - bash -c '[[ $(python -V) == "Python 3.4."* ]] && pip install setuptools==24.0.3 || :'
  - pip install -r requirements.txt
# command to run tests
script:
  - nosetests -s
